import type { Metadata } from "next";

import "./globals.css";
import NavBar from "@/components/NavBar";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className="w-full flex bg-night min-h-screen justify-center text-white items-stretch">
       <NavBar className=""></NavBar>
        {children}</body>
    </html>
  );
}
