import type { Metadata } from "next";

import "./globals.css";
import NavBar from "@/components/NavBar";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className="w-full flex flex-col bg-warm-bg min-h-screen text-warm-text-primary items-stretch">
        <NavBar className="" />
        <main className="w-full flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
